# Generated by Django 5.1 on 2024-08-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0003_storagepackage_profile_storage_limit_storedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("photo", "Photo"),
                    ("document", "Document"),
                    ("music", "Music"),
                    ("video", "Video"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
    ]
