# Generated by Django 5.1 on 2024-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0005_storagepackage_icon_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
