# Generated by Django 5.1 on 2024-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0006_storedfile_file_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="storage_limit",
            field=models.IntegerField(default=10000000000),
        ),
    ]
