# Generated by Django 5.1 on 2024-08-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passwords", "0007_alter_profile_storage_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="storage_limit",
            field=models.IntegerField(default=20000000000),
        ),
    ]
